export * from './pipes.module';
export * from './camelCaseToDash.pipe';
export * from './entity-search.pipe';
export * from './filter.pipe';
export * from './get-date.pipe';
export * from './get-duration.pipe';
export * from './getById.pipe';
export * from './highlightText.pipe';
export * from './htmlToPlaintext.pipe';
export * from './keys.pipe';
export * from './search-resolver.pipe';
export * from './search.pipe';
export * from './time-ago.pipe';
export * from './truncate.pipe';
export * from './chips-char-slice.pipe'
