parameters:
- name: 'project'
  default: ''
  type: string

steps:
# Deploy Azure Static Web App v0
# Build and deploy an Azure Static Web App.
- task: AzureStaticWebApp@0
  inputs:
    #workingDirectory: '$(System.DefaultWorkingDirectory)' # string. Alias: cwd | rootDirectory. Working directory. Default: $(System.DefaultWorkingDirectory).
    app_location: ./dist/${{ project }}
    #config_file_location: # string. Config file location.
    #skip_app_build: # boolean. Skip app build.
    #skip_api_build: # boolean. Skip api build.
    #is_static_export: # boolean. Set static export.
    #verbose: # boolean. Verbose.
    #build_timeout_in_minutes: # string. Build timeout in minutes.
    #azure_static_web_apps_api_token: # string. Azure Static Web Apps api token.
    #deployment_environment: # string. Deployment Environment.
    #production_branch: # string. Production Branch.
    #data_api_location: # string. Data api location.