export const navigations = {
  hash: '',
  data: [
    {
      roleType: 'Administrator',
      menus: [
        {
          active: false,
          icon: null,
          image: null,
          order: '5',
          id: 'user-interface',
          title: 'User Interface',
          type: 'menu-group',
          url: null,
          classes: '{"bg":"green-50-bg","font":"green-fg","border":"green"}',
          hidden: false,
          featureCode: 'navigation.fuse.theme',
          description: null,
          breadcrumb: [],
          children: [
            {
              active: false,
              icon: 'fa-light fa-columns green-fg',
              image: null,
              order: null,
              id: 'zhealthcare-ux-repo',
              title: 'Component Library',
              type: 'menu-item',
              url: '/admin/ux/ui/zhealthcare-component-library',
              classes:
                '{"bg":"green-50-bg","hoverBG":"green-50-hover-bg","activeBG":"green-100-bg"}',
              hidden: false,
              featureCode: 'navigation.fuse.theme',
              description: null,
              breadcrumb: [],
              children: [],
            },
            {
              active: true,
              icon: 'fa-light fa-columns green-fg',
              image: null,
              order: null,
              id: 'zhealthcare-layouts',
              title: 'Layouts',
              type: 'menu-collapsable',
              url: null,
              classes:
                '{"bg":"green-50-bg","hoverBG":"green-50-hover-bg","activeBG":"green-100-bg"}',
              hidden: false,
              featureCode: 'navigation.fuse.theme',
              description: null,
              breadcrumb: [],
              children: [
                {
                  active: false,
                  icon: 'fa-light fa-columns green-fg',
                  image: null,
                  order: null,
                  id: 'zhealthcare-page-layouts',
                  title: 'zhealthcare Page Layouts',
                  type: 'menu-collapsable',
                  url: null,
                  classes:
                    '{"bg":"green-50-bg","hoverBG":"green-50-hover-bg","activeBG":"green-100-bg"}',
                  hidden: false,
                  featureCode: 'navigation.fuse.theme',
                  description: null,
                  breadcrumb: [],
                  children: [
                    {
                      active: false,
                      icon: null,
                      image: null,
                      order: null,
                      id: 'Fullwidth-Page-scroll',
                      title: 'Fullwidth Page scroll',
                      type: 'menu-item',
                      url: '/admin/ux/ui/page-layouts/layouts/fullwidth-page-scroll',
                      classes:
                        '{"bg":"green-50-bg","hoverBG":"green-50-hover-bg","activeBG":"green-100-bg"}',
                      hidden: false,
                      featureCode: 'navigation.fuse.theme',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: null,
                      image: null,
                      order: null,
                      id: 'Fullwidth-Component-Scroll',
                      title: 'Fullwidth Component Scroll',
                      type: 'menu-item',
                      url: '/admin/ux/ui/page-layouts/layouts/fullwidth-component-scroll',
                      classes:
                        '{"bg":"green-50-bg","hoverBG":"green-50-hover-bg","activeBG":"green-100-bg"}',
                      hidden: false,
                      featureCode: 'navigation.fuse.theme',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: null,
                      image: null,
                      order: null,
                      id: 'zhealthcare-layout-Scroll',
                      title: 'Layout Scroll',
                      type: 'menu-item',
                      url: '/admin/ux/ui/zhealthcare-layout-scroll',
                      classes:
                        '{"bg":"green-50-bg","hoverBG":"green-50-hover-bg","activeBG":"green-100-bg"}',
                      hidden: false,
                      featureCode: 'navigation.fuse.theme',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: null,
                      image: null,
                      order: null,
                      id: 'Two-Column',
                      title: 'Two-Column',
                      type: 'menu-item',
                      url: '/admin/ux/ui/page-layouts/layouts/two-column',
                      classes:
                        '{"bg":"green-50-bg","hoverBG":"green-50-hover-bg","activeBG":"green-100-bg"}',
                      hidden: false,
                      featureCode: 'navigation.fuse.theme',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: null,
                      image: null,
                      order: null,
                      id: 'Two-Column-With-Header',
                      title: 'Two Column With Header',
                      type: 'menu-item',
                      url: '/admin/ux/ui/page-layouts/layouts/two-column-with-header',
                      classes:
                        '{"bg":"green-50-bg","hoverBG":"green-50-hover-bg","activeBG":"green-100-bg"}',
                      hidden: false,
                      featureCode: 'navigation.fuse.theme',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: null,
                      image: null,
                      order: null,
                      id: 'Two-Sidebar-Layout',
                      title: 'Two Sidebar Layout',
                      type: 'menu-item',
                      url: '/admin/ux/ui/page-layouts/layouts/two-sidebar-layout',
                      classes:
                        '{"bg":"green-50-bg","hoverBG":"green-50-hover-bg","activeBG":"green-100-bg"}',
                      hidden: false,
                      featureCode: 'navigation.fuse.theme',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                  ],
                },
                {
                  active: false,
                  icon: 'fa-light fa-columns green-fg',
                  image: null,
                  order: null,
                  id: 'left-sidebar',
                  title: 'Left Sidebar Layout',
                  type: 'menu-item',
                  url: '/admin/ux/apps/left-sidebar-layout',
                  classes:
                    '{"bg":"green-50-bg","hoverBG":"green-50-hover-bg","activeBG":"green-100-bg"}',
                  hidden: false,
                  featureCode: 'navigation.fuse.theme',
                  description: null,
                  breadcrumb: [],
                  children: [],
                },
              ],
            }
          ],
        },
      ],
      productName: 'FuseTheme',
      title: 'FuseTheme',
      icon: null,
      partitionKey: null,
      entityName: null,
      id: 'Meta.Navigation.FuseTheme.Administrator',
      _rid: '3Y1yAJ6xvCmmAAAAAAAAAA==',
      _self: 'dbs/3Y1yAA==/colls/3Y1yAJ6xvCk=/docs/3Y1yAJ6xvCmmAAAAAAAAAA==/',
      _ts: 1675933423,
      _etag: '"0000f910-0000-2000-0000-63e4b6ef0000"',
    },
    {
      roleType: 'Administrator',
      menus: [
        {
          active: true,
          icon: 'fa-light  fa-table-cells',
          image: null,
          order: '0',
          id: 'dashboard',
          title: 'Home',
          type: 'menu-item',
          url: '/dashboard',
          classes: '{"bg":"pink-50-bg","font":"pink-fg","border":"pink"}',
          hidden: false,
          featureCode: 'navigation.programme',
          description: null,
          breadcrumb: [],
          children: [],
        },
        {
          active: false,
          icon: 'web',
          image: null,
          order: '1',
          id: 'program',
          title: 'PROGRAM',
          type: 'menu-group',
          url: null,
          classes: '{"bg":"pink-50-bg","font":"pink-fg","border":"pink"}',
          hidden: false,
          featureCode: 'navigation.programme',
          description: null,
          breadcrumb: [],
          children: [
            {
              active: false,
              icon: 'fa-light fa-university pink-fg',
              image: null,
              order: null,
              id: 'program.information',
              title: 'Patients',
              type: 'menu-collapsable',
              url: '/admin/program',
              classes:
                '{"bg":"pink-50-bg","hoverBG":"pink-50-hover-bg","activeBG":"pink-100-bg"}',
              hidden: false,
              featureCode: 'Programme.Basic.Information',
              description:
                'Set up defining attributes of the program including mission, vision, accreditation standards and more.',
              breadcrumb: [],
              children: [
                {
                  active: false,
                  icon: 'fa-light fa-cubes',
                  image: null,
                  order: null,
                  id: 'program-details',
                  title: 'OP-Type',
                  type: 'menu-item',
                  url: 'programdetails',
                  classes: '{"bg":"pink-50-bg","hoverBG":"pink-50-hover-bg","activeBG":"pink-100-bg"}',
                  hidden: false,
                  featureCode: 'Service.Programme.General',
                  description: null,
                  breadcrumb: [],
                  children: [],
                },
                {
                  active: false,
                  icon: 'fa-light fa-cubes',
                  image: null,
                  order: null,
                  id: 'standards',
                  title: 'Patient Type',
                  type: 'menu-item',
                  url: 'standards',
                  classes: '{"bg":"pink-50-bg","hoverBG":"pink-50-hover-bg","activeBG":"pink-100-bg"}',
                  hidden: false,
                  featureCode: 'Service.Programme.Standards',
                  description: null,
                  breadcrumb: [],
                  children: [],
                },
                {
                  active: false,
                  icon: 'fa-light fa-chart-network',
                  image: null,
                  order: null,
                  id: 'campus',
                  title: 'DRG',
                  type: 'menu-item',
                  url: 'campus',
                  classes: '{"bg":"pink-50-bg","hoverBG":"pink-50-hover-bg","activeBG":"pink-100-bg"}',
                  hidden: false,
                  featureCode: 'Service.Programme.Campus',
                  description: null,
                  breadcrumb: [],
                  children: [],
                },
                {
                  active: false,
                  icon: '',
                  image: null,
                  order: null,
                  id: 'external-resources',
                  title: 'Reimb Type Category',
                  type: 'menu-item',
                  url: 'external-resources',
                  classes: '{"bg":"pink-50-bg","hoverBG":"pink-50-hover-bg","activeBG":"pink-100-bg"}',
                  hidden: false,
                  featureCode:
                    'navigation.program.information.external-resources',
                  description: null,
                  breadcrumb: [],
                  children: [],
                },
                {
                  active: true,
                  icon: 'fa-light fa-file-invoice pink-fg',
                  image: null,
                  order: null,
                  id: 'admin.compliance-new',
                  title: 'Query Diagnosis',
                  type: 'menu-item',
                  url: '/admin/compliance-new',
                  classes:
                    '{"bg":"pink-50-bg","hoverBG":"pink-50-hover-bg","activeBG":"pink-100-bg"}',
                  hidden: false,
                  featureCode: 'navigation.admin.compliance-v2',
                  description:
                    'Configure, collect, review and communicate with students about clearance documents for clinical education.',
                  breadcrumb: []
                },
                {
                  active: true,
                  icon: 'fa-light fa-file-invoice pink-fg',
                  image: null,
                  order: null,
                  id: 'admin.compliance-new',
                  title: 'Room Type',
                  type: 'menu-item',
                  url: '/admin/compliance-new',
                  classes:
                    '{"bg":"pink-50-bg","hoverBG":"pink-50-hover-bg","activeBG":"pink-100-bg"}',
                  hidden: false,
                  featureCode: 'navigation.admin.compliance-v2',
                  description:
                    'Configure, collect, review and communicate with students about clearance documents for clinical education.',
                  breadcrumb: []
                }
              ],
            },
            {
              active: false,
              icon: 'fa-light fa-user',
              image: null,
              order: null,
              id: 'admin.profile.header',
              title: 'Transactions',
              type: 'nav-item',
              url: '',
              classes: null,
              hidden: false,
              featureCode: 'navigation.admin.profile.header',
              description: null,
              breadcrumb: [],
              children: [
                {
                  active: true,
                  icon: 'fa-light fa-cogs',
                  image: null,
                  order: null,
                  id: 'admin.configuration',
                  title: 'Setup',
                  type: 'item',
                  url: '/admin/profile/configuration',
                  classes: null,
                  hidden: false,
                  featureCode: 'navigation.admin.configuration',
                  description: null,
                  breadcrumb: [],
                  children: [
                    {
                      active: false,
                      icon: '',
                      image: null,
                      order: null,
                      id: 'setup',
                      title: 'Student Organization',
                      type: 'menu-collapsable',
                      url: 'setup',
                      classes: null,
                      hidden: false,
                      featureCode: 'navigation.admin.configuration.setup',
                      description: null,
                      breadcrumb: [],
                      children: [
                        {
                          active: false,
                          icon: 'fa-light fa-cog',
                          image: null,
                          order: null,
                          id: 'cohort',
                          title: 'Cohort',
                          type: 'menu-item',
                          url: 'cohort',
                          classes: null,
                          hidden: false,
                          featureCode: 'navigation.admin.cohort-setup',
                          description: null,
                          breadcrumb: [],
                          children: [],
                        },
                        {
                          active: false,
                          icon: 'fa-light fa-cog',
                          image: null,
                          order: null,
                          id: 'enrollmentterm',
                          title: 'Enrollment Calendar',
                          type: 'menu-item',
                          url: 'enrollmentterm',
                          classes: null,
                          hidden: false,
                          featureCode: 'navigation.admin.lookup-setup',
                          description: null,
                          breadcrumb: [],
                          children: [],
                        },
                        {
                          active: false,
                          icon: 'fa-light fa-cog',
                          image: null,
                          order: null,
                          id: 'graduationterm',
                          title: 'Graduation Calendar',
                          type: 'menu-item',
                          url: 'graduationterm',
                          classes: null,
                          hidden: false,
                          featureCode: 'navigation.admin.lookup-setup',
                          description: null,
                          breadcrumb: [],
                          children: [],
                        },
                        {
                          active: false,
                          icon: 'fa-light fa-cog',
                          image: null,
                          order: null,
                          id: 'studentcategory',
                          title: 'Student Category',
                          type: 'menu-item',
                          url: 'studentcategory',
                          classes: null,
                          hidden: false,
                          featureCode: 'navigation.admin.lookup-setup',
                          description: null,
                          breadcrumb: [],
                          children: [],
                        },
                        {
                          active: false,
                          icon: 'fa-light fa-cog',
                          image: null,
                          order: null,
                          id: 'campus',
                          title: 'Campus',
                          type: 'menu-item',
                          url: 'campus',
                          classes: null,
                          hidden: false,
                          featureCode: 'navigation.admin.lookup-setup',
                          description: null,
                          breadcrumb: [],
                          children: [],
                        },
                      ],
                    },
                    {
                      active: false,
                      icon: '',
                      image: null,
                      order: null,
                      id: 'studentManagement',
                      title: 'Student Management',
                      type: 'menu-collapsable',
                      url: null,
                      classes: null,
                      hidden: false,
                      featureCode:
                        'navigation.admin.configuration.studentManagement',
                      description: null,
                      breadcrumb: [],
                      children: [
                        {
                          active: false,
                          icon: '',
                          image: null,
                          order: null,
                          id: 'studentImport',
                          title: 'Bulk Import',
                          type: 'menu-item',
                          url: 'student-import',
                          classes: null,
                          hidden: false,
                          featureCode:
                            'navigation.admin.configuration.studentManagement.studentImport',
                          description: null,
                          breadcrumb: [],
                          children: [],
                        },
                        {
                          active: false,
                          icon: '',
                          image: null,
                          order: null,
                          id: 'inviteStudent',
                          title: 'Invite Student',
                          type: 'menu-item',
                          url: 'invite-student',
                          classes: null,
                          hidden: false,
                          featureCode:
                            'navigation.admin.configuration.studentManagement.inviteStudent',
                          description: null,
                          breadcrumb: [],
                          children: [],
                        },
                      ],
                    },
                    {
                      active: false,
                      icon: 'fa-light fa-calendar-check',
                      image: null,
                      order: null,
                      id: 'announcements',
                      title: 'Announcements',
                      type: 'item',
                      url: 'announcements',
                      classes: null,
                      hidden: false,
                      featureCode:
                        'navigation.admin.configuration.announcements',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: 'fa fa-book-reader',
                      image: null,
                      order: null,
                      id: 'resources',
                      title: 'Resources',
                      type: 'item',
                      url: 'resources',
                      classes: null,
                      hidden: false,
                      featureCode: 'navigation.admin.configuration.resources',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: 'fa fa-book-reader',
                      image: null,
                      order: null,
                      id: 'attestation',
                      title: 'Attestations',
                      type: 'item',
                      url: 'attestation',
                      classes: null,
                      hidden: false,
                      featureCode: 'navigation.admin.configuration.attestation',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: 'fa fa-book-reader',
                      image: null,
                      order: null,
                      id: 'programRequirement',
                      title: 'Program Requirements',
                      type: 'item',
                      url: 'program-requirement',
                      classes: null,
                      hidden: false,
                      featureCode:
                        'navigation.admin.configuration.programRequirement',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: 'null',
                      image: null,
                      order: null,
                      id: 'questionnaire',
                      title: 'Additional Profile Details',
                      type: 'item',
                      url: 'questionnaire',
                      classes: null,
                      hidden: false,
                      featureCode:
                        'navigation.admin.configuration.questionnaire',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: '',
                      image: null,
                      order: null,
                      id: 'manage-config',
                      title: 'Configuration',
                      type: 'item',
                      url: 'manage-config',
                      classes: null,
                      hidden: false,
                      featureCode:
                        'navigation.admin.configuration.manage-config',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                  ],
                },
                {
                  active: false,
                  icon: '',
                  image: null,
                  order: null,
                  id: 'student',
                  title: 'Students',
                  type: 'item',
                  url: '/admin/profile/search',
                  classes: null,
                  hidden: false,
                  featureCode: 'navigation.admin.profile.header',
                  description: null,
                  breadcrumb: [],
                  children: [],
                },
                {
                  active: false,
                  icon: '',
                  image: null,
                  order: null,
                  id: 'admin.profile.report',
                  title: 'Reports',
                  type: 'item',
                  url: '/admin/profile/reports',
                  classes: null,
                  hidden: false,
                  featureCode: 'navigation.admin.profile.report',
                  description: null,
                  breadcrumb: [],
                  children: [],
                },
                {
                  active: false,
                  icon: '',
                  image: null,
                  order: null,
                  id: 'admin.profile.dashboard',
                  title: 'Dashboard',
                  type: 'item',
                  url: '/admin/profile/dashboard',
                  classes: null,
                  hidden: false,
                  featureCode: 'navigation.admin.profile.dashboard',
                  description: null,
                  breadcrumb: [],
                  children: [],
                },
              ],
            },
            {
              active: true,
              icon: 'fa-light fa-graduation-cap pink-fg',
              image: null,
              order: null,
              id: 'admin.profile',
              title: 'Reimb Type',
              type: 'menu-item',
              url: '/admin/profile',
              classes:
                '{"bg":"pink-50-bg","hoverBG":"pink-50-hover-bg","activeBG":"pink-100-bg"}',
              hidden: false,
              featureCode: 'navigation.admin.profile',
              description:
                'Manage profiles and demographic information on matriculated students and alumni.',
              breadcrumb: [],
              // children: [
              //   {
              //     active: false,
              //     icon: '',
              //     image: null,
              //     order: null,
              //     id: 'profile',
              //     title: 'Academic Info',
              //     type: 'item',
              //     url: 'academics',
              //     classes: null,
              //     hidden: false,
              //     featureCode: 'navigation.admin.profile.acadamicinfo',
              //     description: null,
              //     breadcrumb: [],
              //     children: [],
              //   },
              //   {
              //     active: false,
              //     icon: '',
              //     image: null,
              //     order: null,
              //     id: 'info',
              //     title: 'Profile Info',
              //     type: 'item',
              //     url: 'info',
              //     classes: null,
              //     hidden: false,
              //     featureCode: 'navigation.admin.profile.info',
              //     description: null,
              //     breadcrumb: [],
              //     children: [],
              //   },
              //   {
              //     active: false,
              //     icon: '',
              //     image: null,
              //     order: null,
              //     id: 'compliance',
              //     title: 'Compliance',
              //     type: 'item',
              //     url: 'compliance',
              //     classes: null,
              //     hidden: false,
              //     featureCode: 'navigation.admin.compliance',
              //     description: null,
              //     breadcrumb: [],
              //     children: [],
              //   },
              //   {
              //     active: false,
              //     icon: '',
              //     image: null,
              //     order: null,
              //     id: 'communications',
              //     title: 'Communications',
              //     type: 'item',
              //     url: 'communications',
              //     classes: null,
              //     hidden: false,
              //     featureCode: 'navigation.admin.profile.communications',
              //     description: null,
              //     breadcrumb: [],
              //     children: [],
              //   },
              //   {
              //     active: false,
              //     icon: '',
              //     image: null,
              //     order: null,
              //     id: 'interventions',
              //     title: 'Interventions',
              //     type: 'item',
              //     url: 'interventions',
              //     classes: null,
              //     hidden: false,
              //     featureCode: 'navigation.admin.profile.interventions',
              //     description: null,
              //     breadcrumb: [],
              //     children: [],
              //   },
              //   {
              //     active: false,
              //     icon: '',
              //     image: null,
              //     order: null,
              //     id: 'ClinicalCoursework',
              //     title: 'Clinical Coursework',
              //     type: 'item',
              //     url: 'clinicalcoursework',
              //     classes: null,
              //     hidden: false,
              //     featureCode: 'navigation.admin.profile.clinicalcoursework',
              //     description: 'ClinicalCoursework',
              //     breadcrumb: [],
              //     children: [],
              //   },
              //   {
              //     active: false,
              //     icon: '',
              //     image: null,
              //     order: null,
              //     id: 'admin.profile.learningActivities',
              //     title: 'Learning Activities',
              //     type: 'item',
              //     url: 'learningactivities',
              //     classes: null,
              //     hidden: false,
              //     featureCode: 'navigation.admin.profile.learningactivities',
              //     description: null,
              //     breadcrumb: [],
              //     children: [
              //       {
              //         active: false,
              //         icon: null,
              //         image: null,
              //         order: null,
              //         id: 'evaluation',
              //         title: 'Forms/Evaluations',
              //         type: 'menu-item',
              //         url: 'evaluations',
              //         classes: null,
              //         hidden: false,
              //         featureCode:
              //           'navigation.admin.learningactivities.evalutions',
              //         description: null,
              //         breadcrumb: [],
              //         children: [],
              //       },
              //       {
              //         active: false,
              //         icon: null,
              //         image: null,
              //         order: null,
              //         id: 'patientlog',
              //         title: 'Patient Log',
              //         type: 'menu-item',
              //         url: 'patientlog',
              //         classes: null,
              //         hidden: false,
              //         featureCode:
              //           'navigation.admin.learningactivities.patientlog',
              //         description: null,
              //         breadcrumb: [],
              //         children: [],
              //       },
              //       {
              //         active: false,
              //         icon: null,
              //         image: null,
              //         order: null,
              //         id: 'timesheet',
              //         title: 'Timesheet',
              //         type: 'menu-item',
              //         url: 'timesheet',
              //         classes: null,
              //         hidden: false,
              //         featureCode:
              //           'navigation.admin.learningactivities.timesheet',
              //         description: null,
              //         breadcrumb: [],
              //         children: [],
              //       },
              //       {
              //         active: false,
              //         icon: null,
              //         image: null,
              //         order: null,
              //         id: 'timeoff',
              //         title: 'Time Off',
              //         type: 'menu-item',
              //         url: 'timeoff',
              //         classes: null,
              //         hidden: false,
              //         featureCode:
              //           'navigation.admin.learningactivities.timeoff',
              //         description: null,
              //         breadcrumb: [],
              //         children: [],
              //       },
              //     ],
              //   },
              // ],
            },
            {
              active: false,
              icon: 'fa-light fa-chalkboard-teacher pink-fg',
              image: null,
              order: null,
              id: 'faculty.information',
              title: 'Query Type',
              type: 'menu-item',
              url: '/admin/faculty',
              classes:
                '{"bg":"pink-50-bg","hoverBG":"pink-50-hover-bg","activeBG":"pink-100-bg"}',
              hidden: false,
              featureCode: 'navigation.Faculty',
              description:
                'View faculty portfolios including teaching responsibility, scholarly productivity and service activities.',
              breadcrumb: [],
              children: [
                {
                  active: false,
                  icon: 'fa-light fa-book-reader',
                  image: null,
                  order: null,
                  id: 'faculty.details',
                  title: 'faculty Details',
                  type: 'menu-item',
                  url: '/admin/facultydetails',
                  classes: null,
                  hidden: false,
                  featureCode: 'navigation.faculty.details',
                  description: null,
                  breadcrumb: [],
                  children: [
                    {
                      active: false,
                      icon: 'fa-light fa-address-card',
                      image: null,
                      order: null,
                      id: 'faculty.profile',
                      title: 'Profile Info',
                      type: 'menu-item',
                      url: 'profile',
                      classes: null,
                      hidden: false,
                      featureCode: 'navigation.faculty.profile',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: 'fa-light fa-chalkboard-teacher',
                      image: null,
                      order: null,
                      id: 'faculty.teaching',
                      title: 'Teaching',
                      type: 'menu-item',
                      url: 'teaching',
                      classes: null,
                      hidden: false,
                      featureCode: 'navigation.faculty.teachings',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: 'fa-light fa-diploma',
                      image: null,
                      order: null,
                      id: 'faculty.scholarship',
                      title: 'Scholarship',
                      type: 'menu-item',
                      url: 'scholarship',
                      classes: null,
                      hidden: false,
                      featureCode: 'navigation.faculty.scholarship',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: 'fa-light fa-handshake',
                      image: null,
                      order: null,
                      id: 'faculty.service ',
                      title: 'Service',
                      type: 'menu-item',
                      url: 'service',
                      classes: null,
                      hidden: false,
                      featureCode: 'navigation.faculty.service',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: 'fa-light fa-chart-network',
                      image: null,
                      order: null,
                      id: 'faculty.associations',
                      title: 'Associations',
                      type: 'menu-collapsable',
                      url: '/admin/associations',
                      classes: null,
                      hidden: false,
                      featureCode: 'navigation.faculty.associations',
                      description: null,
                      breadcrumb: [],
                      children: [
                        {
                          active: false,
                          icon: '',
                          image: null,
                          order: null,
                          id: 'faculty.courses',
                          title: 'Courses',
                          type: 'menu-item',
                          url: 'course',
                          classes: null,
                          hidden: false,
                          featureCode: 'navigation.faculty.course',
                          description: null,
                          breadcrumb: [],
                          children: [],
                        },
                        {
                          active: false,
                          icon: '',
                          image: null,
                          order: null,
                          id: 'faculty.student',
                          title: 'Students',
                          type: 'menu-item',
                          url: 'students',
                          classes: null,
                          hidden: false,
                          featureCode: 'navigation.faculty.student',
                          description: null,
                          breadcrumb: [],
                          children: [],
                        },
                        {
                          active: false,
                          icon: '',
                          image: null,
                          order: null,
                          id: 'faculty.placements',
                          title: 'Placements',
                          type: 'menu-item',
                          url: 'placements',
                          classes: null,
                          hidden: false,
                          featureCode: 'navigation.faculty.placement',
                          description: null,
                          breadcrumb: [],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              active: false,
              icon: 'fa-light fa-file-invoice pink-fg',
              image: null,
              order: null,
              id: 'admin.compliance',
              title: 'Response Type',
              type: 'menu-item',
              url: '/admin/compliance',
              classes:
                '{"bg":"pink-50-bg","hoverBG":"pink-50-hover-bg","activeBG":"pink-100-bg"}',
              hidden: false,
              featureCode: 'navigation.admin.compliance',
              description:
                'Configure, collect, review and communicate with students about clearance documents for clinical education.',
              breadcrumb: [],
              children: [
                {
                  active: false,
                  icon: 'fa fa-book-reader',
                  image: null,
                  order: null,
                  id: 'complianceRequirements',
                  title: 'Setup',
                  type: 'item',
                  url: 'setup',
                  classes: null,
                  hidden: false,
                  featureCode:
                    'navigation.admin.configuration.complianceRequirements',
                  description: null,
                  breadcrumb: [],
                  children: [],
                },
                {
                  active: false,
                  icon: '',
                  image: null,
                  order: null,
                  id: 'dashboard',
                  title: 'Dashboard',
                  type: 'item',
                  url: 'dashboard',
                  classes: null,
                  hidden: false,
                  featureCode: 'navigation.admin.compliance.dashboard',
                  description: null,
                  breadcrumb: [],
                  children: [],
                },
                {
                  active: false,
                  icon: '',
                  image: null,
                  order: null,
                  id: 'summary',
                  title: 'Summary',
                  type: 'item',
                  url: 'summary',
                  classes: null,
                  hidden: false,
                  featureCode: 'navigation.admin.compliance.summary',
                  description: null,
                  breadcrumb: [],
                  children: [],
                },
                {
                  active: false,
                  icon: '',
                  image: null,
                  order: null,
                  id: 'notification',
                  title: 'Notifications',
                  type: 'item',
                  url: 'notification',
                  classes: null,
                  hidden: false,
                  featureCode: 'navigation.admin.compliance.notification',
                  description: null,
                  breadcrumb: [],
                  children: [],
                },
                {
                  active: false,
                  icon: '',
                  image: null,
                  order: null,
                  id: 'admin.compliance.report',
                  title: 'Reports',
                  type: 'item',
                  url: '/admin/compliance/reports',
                  classes: null,
                  hidden: false,
                  featureCode: 'navigation.admin.compliance.report',
                  description: null,
                  breadcrumb: [],
                  children: [
                    {
                      active: false,
                      icon: '',
                      image: null,
                      order: null,
                      id: 'pending',
                      title: 'Pending Review',
                      type: 'item',
                      url: '/admin/compliance/reports/pending',
                      classes: null,
                      hidden: false,
                      featureCode: 'navigation.admin.compliance.report.pending',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: '',
                      image: null,
                      order: null,
                      id: 'expiry',
                      title: 'Expiring, Expired',
                      type: 'item',
                      url: '/admin/compliance/reports/expiry',
                      classes: null,
                      hidden: false,
                      featureCode: 'navigation.admin.compliance.report.expiry',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: '',
                      image: null,
                      order: null,
                      id: 'universal',
                      title: 'Universal Requirements',
                      type: 'item',
                      url: '/admin/compliance/reports/universal',
                      classes: null,
                      hidden: false,
                      featureCode:
                        'navigation.admin.compliance.report.universal',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              active: false,
              icon: 'fa-light fa-file-invoice pink-fg',
              image: null,
              order: null,
              id: 'admin.compliance-new',
              title: 'Physician',
              type: 'menu-item',
              url: '/admin/compliance-new',
              classes:
                '{"bg":"pink-50-bg","hoverBG":"pink-50-hover-bg","activeBG":"pink-100-bg"}',
              hidden: false,
              featureCode: 'navigation.admin.compliance-v2',
              description:
                'Configure, collect, review and communicate with students about clearance documents for clinical education.',
              breadcrumb: [],
              children: [
                {
                  active: false,
                  icon: 'fa fa-book-reader',
                  image: null,
                  order: null,
                  id: 'complianceRequirements',
                  title: 'Setup',
                  type: 'item',
                  url: 'setup',
                  classes: null,
                  hidden: false,
                  featureCode:
                    'navigation.admin.configuration.complianceRequirements-v2',
                  description: null,
                  breadcrumb: [],
                  children: [],
                },
                {
                  active: false,
                  icon: '',
                  image: null,
                  order: null,
                  id: 'compliance.admin.home',
                  title: 'Home',
                  type: 'menu-item',
                  url: 'home',
                  classes: null,
                  hidden: false,
                  featureCode: 'navigation.admin.compliance.home',
                  description: null,
                  breadcrumb: [],
                  children: [
                    {
                      active: false,
                      icon: '',
                      image: null,
                      order: null,
                      id: 'compliance.mapping',
                      title: 'Mapping',
                      type: 'item',
                      url: 'mapping',
                      classes: null,
                      hidden: false,
                      featureCode: 'navigation.admin.compliance.mapping',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: '',
                      image: null,
                      order: null,
                      id: 'dashboard',
                      title: 'Dashboard',
                      type: 'item',
                      url: 'dashboard',
                      classes: null,
                      hidden: false,
                      featureCode: 'navigation.admin.compliance.dashboard-v2',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: '',
                      image: null,
                      order: null,
                      id: 'summary',
                      title: 'Summary',
                      type: 'item',
                      url: 'summary',
                      classes: null,
                      hidden: false,
                      featureCode: 'navigation.admin.compliance.summary-v2',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                  ],
                },
                {
                  active: false,
                  icon: '',
                  image: null,
                  order: null,
                  id: 'admin.compliance.report',
                  title: 'Reports',
                  type: 'item',
                  url: '/admin/compliance/reports',
                  classes: null,
                  hidden: false,
                  featureCode: 'navigation.admin.compliance.report-v2',
                  description: null,
                  breadcrumb: [],
                  children: [
                    {
                      active: false,
                      icon: '',
                      image: null,
                      order: null,
                      id: 'pending',
                      title: 'Pending Review',
                      type: 'item',
                      url: '/admin/compliance/reports/pending',
                      classes: null,
                      hidden: false,
                      featureCode:
                        'navigation.admin.compliance.report.pending-v2',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: '',
                      image: null,
                      order: null,
                      id: 'expiry',
                      title: 'Expiring, Expired',
                      type: 'item',
                      url: '/admin/compliance/reports/expiry',
                      classes: null,
                      hidden: false,
                      featureCode:
                        'navigation.admin.compliance.report.expiry-v2',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                    {
                      active: false,
                      icon: '',
                      image: null,
                      order: null,
                      id: 'universal',
                      title: 'Universal Requirements',
                      type: 'item',
                      url: '/admin/compliance/reports/universal',
                      classes: null,
                      hidden: false,
                      featureCode:
                        'navigation.admin.compliance.report.universal-v2',
                      description: null,
                      breadcrumb: [],
                      children: [],
                    },
                  ],
                },
              ],
            }
          ],
        },
        // {
        //   active: false,
        //   icon: 'web',
        //   image: '',
        //   order: '2',
        //   id: 'apps',
        //   title: 'Curriculum Management',
        //   type: 'menu-group',
        //   url: null,
        //   classes: '{"bg":"orange-50-bg","font":"orange-fg","border":"orange"}',
        //   hidden: false,
        //   featureCode: 'navigation.plan',
        //   description: null,
        //   breadcrumb: [],
        //   children: [
        //     {
        //       active: false,
        //       icon: 'fa-light fa-books orange-fg',
        //       image: null,
        //       order: null,
        //       id: 'program.course',
        //       title: 'Courses',
        //       type: 'menu-item',
        //       url: '/admin/curriculum',
        //       classes:
        //         '{"bg":"orange-50-bg","hoverBG":"orange-50-hover-bg","activeBG":"orange-100-bg"}',
        //       hidden: false,
        //       featureCode: 'navigation.program.Courses',
        //       description:
        //         'Enter, organize and manage courses including course documents, schedules, resources and registration.',
        //       breadcrumb: [],
        //       children: [
        //         {
        //           active: false,
        //           icon: 'fa-light  fa-book-reader',
        //           image: null,
        //           order: null,
        //           id: 'courses.setup',
        //           title: 'Setup',
        //           type: 'menu-item',
        //           url: 'setup',
        //           classes: null,
        //           hidden: false,
        //           featureCode: 'navigation.program.courses.setup',
        //           description: null,
        //           breadcrumb: [],
        //           children: [
        //             {
        //               active: false,
        //               icon: '',
        //               image: null,
        //               order: null,
        //               id: 'course-measures',
        //               title: 'Course Measures',
        //               type: 'item',
        //               url: 'coursemeasures',
        //               classes: null,
        //               hidden: false,
        //               featureCode: 'Service.course.setup.coursemeasures',
        //               description: null,
        //               breadcrumb: [],
        //               children: [],
        //             },
        //             {
        //               active: false,
        //               icon: '',
        //               image: null,
        //               order: null,
        //               id: 'attributes',
        //               title: 'Attributes',
        //               type: 'item',
        //               url: 'attributes',
        //               classes: null,
        //               hidden: false,
        //               featureCode: 'Service.courses.setup.attributes',
        //               description: null,
        //               breadcrumb: [],
        //               children: [],
        //             },
        //             {
        //               active: false,
        //               icon: 'fas fa-cubes',
        //               image: null,
        //               order: null,
        //               id: 'admin.program.learningActivities',
        //               title: 'Learning Activity',
        //               type: 'menu-item',
        //               url: 'learningactivities',
        //               classes: null,
        //               hidden: false,
        //               featureCode:
        //                 'navigation.admin.profile.learningactivities',
        //               description: null,
        //               breadcrumb: [],
        //               children: [],
        //             },
        //           ],
        //         },
        //         {
        //           active: false,
        //           icon: 'fa-light fa-book-reader',
        //           image: null,
        //           order: null,
        //           id: 'courses.master',
        //           title: 'Course Catalog',
        //           type: 'menu-item',
        //           url: 'courses',
        //           classes: null,
        //           hidden: false,
        //           featureCode: 'navigation.program.courses.master',
        //           description: null,
        //           breadcrumb: [],
        //           children: [],
        //         },
        //         {
        //           active: false,
        //           icon: 'fa-light fa-book-reader',
        //           image: null,
        //           order: null,
        //           id: 'course.offering',
        //           title: 'Course offerings',
        //           type: 'menu-item',
        //           url: 'courseofferings',
        //           classes: null,
        //           hidden: false,
        //           featureCode: 'navigation.curriculum.offering',
        //           description: null,
        //           breadcrumb: [],
        //           children: [
        //             {
        //               active: false,
        //               icon: 'fa-light fa-book-reader',
        //               image: null,
        //               order: null,
        //               id: 'course.details',
        //               title: 'Course Details',
        //               type: 'menu-item',
        //               url: '/admin/coursedetails',
        //               classes: null,
        //               hidden: false,
        //               featureCode: 'navigation.course.details',
        //               description: null,
        //               breadcrumb: [],
        //               children: [
        //                 {
        //                   active: false,
        //                   icon: 'fa-light fa-books',
        //                   image: null,
        //                   order: null,
        //                   id: 'course.information',
        //                   title: 'Course information',
        //                   type: 'menu-collapsable',
        //                   url: null,
        //                   classes: null,
        //                   hidden: false,
        //                   featureCode: 'navigation.course.information',
        //                   description: null,
        //                   breadcrumb: [],
        //                   children: [
        //                     {
        //                       active: false,
        //                       icon: 'fa-light fa-book-reader',
        //                       image: null,
        //                       order: null,
        //                       id: 'courses.about',
        //                       title: 'About',
        //                       type: 'menu-item',
        //                       url: 'about',
        //                       classes: null,
        //                       hidden: false,
        //                       featureCode: 'navigation.course.about',
        //                       description: null,
        //                       breadcrumb: [],
        //                       children: [],
        //                     },
        //                     {
        //                       active: false,
        //                       icon: 'fa-light fa-book-reader',
        //                       image: null,
        //                       order: null,
        //                       id: 'course.measure',
        //                       title: 'Measures',
        //                       type: 'menu-item',
        //                       url: 'measure',
        //                       classes: null,
        //                       hidden: false,
        //                       featureCode: 'navigation.course.measure',
        //                       description: null,
        //                       breadcrumb: [],
        //                       children: [],
        //                     },
        //                     {
        //                       active: false,
        //                       icon: 'fa-light fa-book-reader',
        //                       image: null,
        //                       order: null,
        //                       id: 'course.resource',
        //                       title: 'Resources',
        //                       type: 'menu-item',
        //                       url: 'resource',
        //                       classes: null,
        //                       hidden: false,
        //                       featureCode: 'navigation.course.resource',
        //                       description: null,
        //                       breadcrumb: [],
        //                       children: [],
        //                     },
        //                     {
        //                       active: false,
        //                       icon: 'fa-light fa-book-reader',
        //                       image: null,
        //                       order: null,
        //                       id: 'course.event',
        //                       title: 'Event schedule',
        //                       type: 'menu-item',
        //                       url: 'event',
        //                       classes: null,
        //                       hidden: false,
        //                       featureCode: 'navigation.course.event',
        //                       description: null,
        //                       breadcrumb: [],
        //                       children: [],
        //                     },
        //                   ],
        //                 },
        //                 {
        //                   active: true,
        //                   icon: 'fa-light fa-user',
        //                   image: null,
        //                   order: null,
        //                   id: 'course.student.registration',
        //                   title: 'Students',
        //                   type: 'menu-collapsable',
        //                   url: '/admin/profile',
        //                   classes: null,
        //                   hidden: false,
        //                   featureCode: 'navigation.student.registration',
        //                   description: null,
        //                   breadcrumb: [],
        //                   children: [
        //                     {
        //                       active: false,
        //                       icon: '',
        //                       image: null,
        //                       order: null,
        //                       id: 'profile.registration',
        //                       title: 'Student Registration',
        //                       type: 'item',
        //                       url: 'registration',
        //                       classes: null,
        //                       hidden: false,
        //                       featureCode:
        //                         'navigation.student.registration.info',
        //                       description: null,
        //                       breadcrumb: [],
        //                       children: [],
        //                     },
        //                     {
        //                       active: false,
        //                       icon: 'fa-light fa-file-alt',
        //                       image: null,
        //                       order: null,
        //                       id: 'course.compliance',
        //                       title: 'Compliance',
        //                       type: 'menu-item',
        //                       url: 'compliance',
        //                       classes: null,
        //                       hidden: false,
        //                       featureCode: 'navigation.course.newcompliance',
        //                       description: null,
        //                       breadcrumb: [],
        //                       children: [],
        //                     },
        //                   ],
        //                 },
        //                 {
        //                   active: false,
        //                   icon: 'fa-light fa-bullhorn',
        //                   image: null,
        //                   order: null,
        //                   id: 'courseLevel.announcements',
        //                   title: 'Announcements',
        //                   type: 'item',
        //                   url: 'announcements',
        //                   classes: null,
        //                   hidden: false,
        //                   featureCode: 'navigation.course.announcements',
        //                   description: null,
        //                   breadcrumb: [],
        //                   children: [],
        //                 },
        //                 {
        //                   active: false,
        //                   icon: 'fa-light fa-chalkboard-teacher',
        //                   image: null,
        //                   order: null,
        //                   id: 'admin.courseactivity',
        //                   title: 'Learning activities',
        //                   type: 'menu-collapsable',
        //                   url: '/admin/courseactivity',
        //                   classes: null,
        //                   hidden: false,
        //                   featureCode: 'navigation.course.courseactivity',
        //                   description: null,
        //                   breadcrumb: [],
        //                   children: [
        //                     {
        //                       active: false,
        //                       icon: '',
        //                       image: null,
        //                       order: null,
        //                       id: 'steps.lamsetup',
        //                       title: 'Setup',
        //                       type: 'item',
        //                       url: 'activities',
        //                       classes: null,
        //                       hidden: false,
        //                       featureCode:
        //                         'navigation.admin.evaluation.activation',
        //                       description: null,
        //                       breadcrumb: [],
        //                       children: [],
        //                     },
        //                     {
        //                       active: false,
        //                       icon: '',
        //                       image: null,
        //                       order: null,
        //                       id: 'steps.lam.review',
        //                       title: 'Review',
        //                       type: 'item',
        //                       url: null,
        //                       classes: null,
        //                       hidden: false,
        //                       featureCode:
        //                         'navigation.admin.evaluation.management.summary',
        //                       description: null,
        //                       breadcrumb: [],
        //                       children: [],
        //                     },
        //                   ],
        //                 },
        //                 {
        //                   active: false,
        //                   icon: 'fa-light fa-hospital-user',
        //                   image: null,
        //                   order: null,
        //                   id: 'admin.placement',
        //                   title: 'Placements',
        //                   type: 'menu-collapsable',
        //                   url: 'null',
        //                   classes: null,
        //                   hidden: false,
        //                   featureCode: 'navigation.course.placement',
        //                   description: null,
        //                   breadcrumb: [],
        //                   children: [
        //                     {
        //                       active: false,
        //                       icon: '',
        //                       image: null,
        //                       order: null,
        //                       id: 'steps.rotationsetup',
        //                       title: 'Rotation setup',
        //                       type: 'item',
        //                       url: 'rotationsetupbycourse',
        //                       classes: null,
        //                       hidden: false,
        //                       featureCode:
        //                         'navigation.admin.steps.rotationsetup',
        //                       description: null,
        //                       breadcrumb: [],
        //                       children: [],
        //                     },
        //                     {
        //                       active: false,
        //                       icon: '',
        //                       image: null,
        //                       order: null,
        //                       id: 'steps.wishlist',
        //                       title: 'Wishlist',
        //                       type: 'item',
        //                       url: 'course-wishlist',
        //                       classes: null,
        //                       hidden: false,
        //                       featureCode: 'navigation.admin.steps.wishlist',
        //                       description: null,
        //                       breadcrumb: [],
        //                       children: [
        //                         {
        //                           active: false,
        //                           icon: '',
        //                           image: null,
        //                           order: null,
        //                           id: 'steps.wishlist.edit',
        //                           title: 'Wishlist',
        //                           type: 'item',
        //                           url: 'edit',
        //                           classes: null,
        //                           hidden: false,
        //                           featureCode:
        //                             'navigation.admin.steps.wishlist',
        //                           description: null,
        //                           breadcrumb: [],
        //                           children: [
        //                             {
        //                               active: false,
        //                               icon: '',
        //                               image: null,
        //                               order: null,
        //                               id: 'course.steps.wishlist.configuration',
        //                               title: 'Setup',
        //                               type: 'item',
        //                               url: 'configuration',
        //                               classes: null,
        //                               hidden: false,
        //                               featureCode:
        //                                 'navigation.admin.steps.wishlist',
        //                               description: null,
        //                               breadcrumb: [],
        //                               children: [],
        //                             },
        //                             {
        //                               active: false,
        //                               icon: '',
        //                               image: null,
        //                               order: null,
        //                               id: 'course.steps.wishlist.managewishlist',
        //                               title: 'Wishlist Management',
        //                               type: 'item',
        //                               url: 'wishlist-management',
        //                               classes: null,
        //                               hidden: false,
        //                               featureCode:
        //                                 'navigation.admin.steps.wishlist',
        //                               description: null,
        //                               breadcrumb: [],
        //                               children: [],
        //                             },
        //                           ],
        //                         },
        //                       ],
        //                     },
        //                     {
        //                       active: false,
        //                       icon: '',
        //                       image: null,
        //                       order: null,
        //                       id: 'steps.slotsAndPlacements',
        //                       title: 'Slots and Placements',
        //                       type: 'item',
        //                       url: 'slotsandplacements',
        //                       classes: null,
        //                       hidden: false,
        //                       featureCode:
        //                         'navigation.admin.steps.slotsAndPlacements',
        //                       description: null,
        //                       breadcrumb: [],
        //                       children: [],
        //                     },
        //                   ],
        //                 },
        //                 {
        //                   active: false,
        //                   icon: 'fa-light fa-books',
        //                   image: null,
        //                   order: null,
        //                   id: 'course.surveys',
        //                   title: 'Post course surveys',
        //                   type: 'menu-collapsable',
        //                   url: null,
        //                   classes: null,
        //                   hidden: false,
        //                   featureCode: 'navigation.course.surveys',
        //                   description: null,
        //                   breadcrumb: [],
        //                   children: [
        //                     {
        //                       active: false,
        //                       icon: '',
        //                       image: null,
        //                       order: null,
        //                       id: 'courses.surveys.setup',
        //                       title: 'Setup',
        //                       type: 'menu-item',
        //                       url: 'surveys/setup',
        //                       classes: null,
        //                       hidden: false,
        //                       featureCode: 'navigation.course.surveys.setup',
        //                       description: null,
        //                       breadcrumb: [],
        //                       children: [],
        //                     },
        //                     {
        //                       active: false,
        //                       icon: '',
        //                       image: null,
        //                       order: null,
        //                       id: 'course.surveys.review',
        //                       title: 'Review',
        //                       type: 'menu-item',
        //                       url: 'surveys/review',
        //                       classes: null,
        //                       hidden: false,
        //                       featureCode: 'navigation.course.surveys.review',
        //                       description: null,
        //                       breadcrumb: [],
        //                       children: [],
        //                     },
        //                   ],
        //                 },
        //               ],
        //             },
        //           ],
        //         },
        //         {
        //           active: false,
        //           icon: 'fa-light fa-book-reader',
        //           image: null,
        //           order: null,
        //           id: 'courses.catalog',
        //           title: 'Curriculum Grid',
        //           type: 'menu-item',
        //           url: 'catalog',
        //           classes: null,
        //           hidden: false,
        //           featureCode: 'navigation.program.information',
        //           description: null,
        //           breadcrumb: [],
        //           children: [
        //             {
        //               active: false,
        //               icon: 'fa-light fa-book-reader',
        //               image: null,
        //               order: null,
        //               id: 'curriculum.details',
        //               title: 'Course Details',
        //               type: 'menu-item',
        //               url: '/admin/curriculumdetails',
        //               classes: null,
        //               hidden: false,
        //               featureCode: 'navigation.curriculum.details',
        //               description: null,
        //               breadcrumb: [],
        //               children: [],
        //             },
        //             {
        //               active: false,
        //               icon: 'fa-light fa-book-reader',
        //               image: null,
        //               order: null,
        //               id: 'curriculum.details.wizard',
        //               title: 'Details',
        //               type: 'menu-item',
        //               url: 'details',
        //               classes: null,
        //               hidden: false,
        //               featureCode: 'navigation.curriculum.details.wizard',
        //               description: null,
        //               breadcrumb: [],
        //               children: [],
        //             },
        //             {
        //               active: false,
        //               icon: 'fa-light fa-book-reader',
        //               image: null,
        //               order: null,
        //               id: 'curriculum.course.offering',
        //               title: 'Course offering',
        //               type: 'menu-item',
        //               url: 'offering',
        //               classes: null,
        //               hidden: false,
        //               featureCode: 'navigation.curriculum.course.offering',
        //               description: null,
        //               breadcrumb: [],
        //               children: [],
        //             },
        //             {
        //               active: false,
        //               icon: 'fa-light fa-book-reader',
        //               image: null,
        //               order: null,
        //               id: 'curriculum.grid',
        //               title: 'Curriculum grid',
        //               type: 'menu-item',
        //               url: 'grid',
        //               classes: null,
        //               hidden: false,
        //               featureCode: 'navigation.curriculum.grid',
        //               description: null,
        //               breadcrumb: [],
        //               children: [],
        //             },
        //           ],
        //         },
        //       ],
        //     },
        //     {
        //       active: false,
        //       icon: 'fa-light fa-sitemap orange-fg',
        //       image: null,
        //       order: null,
        //       id: 'mapping',
        //       title: 'Mapping',
        //       type: 'menu-item',
        //       url: 'admin/mapping',
        //       classes:
        //         '{"bg":"orange-50-bg","hoverBG":"orange-50-hover-bg","activeBG":"orange-100-bg"}',
        //       hidden: false,
        //       featureCode: 'Plan.Mapping',
        //       description:
        //         'Connect objectives and measures to accrediation standards, program goals and more.',
        //       breadcrumb: [],
        //       children: [
        //         {
        //           active: false,
        //           icon: 'fa-light fa-code-merge',
        //           image: null,
        //           order: null,
        //           id: 'mapping-course',
        //           title: 'Mapping Course',
        //           type: 'menu-item',
        //           url: 'course',
        //           classes: null,
        //           hidden: false,
        //           featureCode: 'Service.Mapping',
        //           description: null,
        //           breadcrumb: [],
        //           children: [],
        //         },
        //       ],
        //     },
        //     {
        //       active: false,
        //       icon: 'fa-light fa-chart-line orange-fg',
        //       image: null,
        //       order: null,
        //       id: 'plan.report',
        //       title: 'Mapping Reports',
        //       type: 'menu-item',
        //       url: 'admin/report',
        //       classes:
        //         '{"bg":"orange-50-bg","hoverBG":"orange-50-hover-bg","activeBG":"orange-100-bg"}',
        //       hidden: false,
        //       featureCode: 'Plan.Report',
        //       description:
        //         'Visualize your curriculum map to find gaps or ensure even coverage of content.',
        //       breadcrumb: [],
        //       children: [],
        //     },
        //   ],
        // },
      ],
      productName: 'plan',
      title: 'plan',
      icon: null,
      partitionKey: null,
      entityName: null,
      id: 'Meta.Navigation.Plan.Administrator',
      _rid: '3Y1yAJ6xvClGAQAAAAAAAA==',
      _self: 'dbs/3Y1yAA==/colls/3Y1yAJ6xvCk=/docs/3Y1yAJ6xvClGAQAAAAAAAA==/',
      _ts: 1677563822,
      _etag: '"1900aa35-0000-2000-0000-63fd97ae0000"',
    },
  ],
  isModified: true,
};
