name: $(Date:yyyyMMdd)$(Rev:.r)

on:
  workflow_dispatch:
    inputs:
      project:
        required: true
        default: 'host'

env:
  AZURE_WEBAPP_NAME: 'zcds'
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '16.x'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install and build
      run: |
        npm ci -f
        npx nx build remote --configuration=development

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ./dist/apps/remote

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with:
            name: artifacts
        - uses: azure/login@v1
          name: Login to Azure
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: 'Deploy to Azure WebApp'
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        - name: logout
          run: |
            az logout
